spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
            redirect-uri: http://localhost:8082/login/oauth2/code/cognito
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuer-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/${COGNITO_USERPOOL_ID}
            authorization-uri: ${COGNITO_DOMAIN}/login

server:
  port: 8082

environments:
  after-auth-redirect-url: ${REDIRECT_PATH}
  login-error-redirect-url: ${REDIRECT_PATH}
  cognito:
    user-pool-id: ${COGNITO_USERPOOL_ID}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    session-token: ${AWS_SESSION_TOKEN}
