spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
            redirect-uri: http://localhost:8082/login/oauth2/code/cognito
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuer-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/${COGNITO_USERPOOL_ID}
            authorization-uri: ${COGNITO_DOMAIN}/oauth2/authorize

server:
  port: 8082

environments:
  after-auth-redirect-url: ${REDIRECT_PATH}
  login-error-redirect-url: ${REDIRECT_PATH}
