AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool and Client for ogata-cognito

Parameters:
  CognitoCustomDomainPrefix:
    Type: String

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ogata-cognito
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      MfaConfiguration: 'OFF'
      UserPoolAddOns:
        AdvancedSecurityMode: ENFORCED
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: allowDomain
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: companyUUID
          AttributeDataType: String
          Mutable: true
          Required: false
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: ogata-user-domain
      UserPoolId: !Ref CognitoUserPool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: cognito-auth
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: true
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      CallbackURLs:
        - http://localhost:8082/login/oauth2/code/cognito
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true

  CognitoUserPoolGroupAdmin:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: ADMIN
      UserPoolId: !Ref CognitoUserPool

  CognitoUserPoolGroupManager:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: MANAGER
      UserPoolId: !Ref CognitoUserPool

  CognitoUserPoolGroupEmployee:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: EMPLOYEE
      UserPoolId: !Ref CognitoUserPool

Outputs:
  UserPoolId:
    Value: !Ref CognitoUserPool
    Description: ID of the Cognito User Pool
  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Description: ID of the Cognito User Pool Client
  CognitoDomain:
    Value: !Sub https://${CognitoUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com
    Description: Cognito Domain URL
